### ISSUE TITLE
只能清除画者的画布

### ISSUE THREAD

**Issue by ycjcl868** [zhoulijie/draw-something#1]
![image](https://cloud.githubusercontent.com/assets/13595509/21523767/f01b6c7c-cd4b-11e6-8434-5069e2e51da6.png)
server.js改成红框代码后，正常！
分析了一下：
`socket.emit('showBoardClearArea')`只是向建立该连接的客户端广播（即画者）
`io.sockets.emit('showBoardClearArea');`是向所有建立连接的客户端广播（即画者+猜者）

**Comment by zhoulijie** [comment]
非常感谢！已经修改
